name: Github To Gitee for org third-items

on:
  push:
  #branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 20:00 -> CST (China) 4:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 20 * * *'
    #- cron: '0 0/5 * * *'
      #pull_request:
      #branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Github To Gitee for org third-items
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/third-items   # 源端账户名(github)
          dst: gitee/third-items    # 目的端账户名(gitee)
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
          dst_token: ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
          account_type: org
          clone_style: ssh
          #static_list: 'mindspore,mindinsight,mindarmour,graphengine,docs,book,community,ms-operator,akg,course,hub,serving,mindquantum,xai,models,mindscience,contrib,reinforcement'
          force_update: true
          #black_list: 'infrastructure'
          debug: true