name: Gitee To Github for org whd-frame

on:
  push:
  #branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 20:00 -> CST (China) 4:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 23 * * *'
      #- cron: '0 0/5 * * *'
      #pull_request:
      #branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Gitee To Github for org whd-frame # 名字随便起
        uses: Yikun/hub-mirror-action@v1.0  # 使用Yikun/hub-mirror-action
        with:
          src: gitee/whd-frame   # 源端账户名(github)
          dst: github/whd-frame    # 目的端账户名(gitee)
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
          dst_token: ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
          account_type: org  # 账户类型
          clone_style: "ssh"  # 使用https方式进行clone，也可以使用ssh
          debug: true  # 启用后会显示所有执行命令
          force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
          #static_list: "python-nianbao-struct"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
          timeout: '600s'  # git超时设置，超时后会自动重试git操作
